// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
)

const recordAuditEvent = `-- name: RecordAuditEvent :exec
INSERT INTO audit_log (id, org_id, actor_user_id, action, target_type, target_id, metadata, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type RecordAuditEventParams struct {
	ID          uuid.UUID
	OrgID       *uuid.UUID
	ActorUserID *uuid.UUID
	Action      string
	TargetType  string
	TargetID    *uuid.UUID
	Metadata    []byte
	Ip          *netip.Addr
}

func (q *Queries) RecordAuditEvent(ctx context.Context, arg RecordAuditEventParams) error {
	_, err := q.db.Exec(ctx, recordAuditEvent,
		arg.ID,
		arg.OrgID,
		arg.ActorUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
		arg.Ip,
	)
	return err
}
