// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const allocatePort = `-- name: AllocatePort :one
INSERT INTO port_allocations (id, org_id, server_id, port, service_id, purpose)
SELECT $1, $2, $3, candidate, $4, $5
FROM generate_series($6::int, $7::int) AS candidate
WHERE NOT EXISTS (
    SELECT 1 FROM port_allocations existing
    WHERE existing.server_id = $3 AND existing.port = candidate
)
ORDER BY candidate
LIMIT 1
RETURNING id, org_id, server_id, port, service_id, purpose, created_at
`

type AllocatePortParams struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	ServerID  uuid.UUID
	ServiceID *uuid.UUID
	Purpose   string
	Column6   int32
	Column7   int32
}

// Takes the lowest free port in the range, so allocations stay compact and predictable.
func (q *Queries) AllocatePort(ctx context.Context, arg AllocatePortParams) (PortAllocation, error) {
	row := q.db.QueryRow(ctx, allocatePort,
		arg.ID,
		arg.OrgID,
		arg.ServerID,
		arg.ServiceID,
		arg.Purpose,
		arg.Column6,
		arg.Column7,
	)
	var i PortAllocation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ServerID,
		&i.Port,
		&i.ServiceID,
		&i.Purpose,
		&i.CreatedAt,
	)
	return i, err
}

const appendDeploymentLog = `-- name: AppendDeploymentLog :exec
INSERT INTO deployment_logs (id, org_id, deployment_id, stream, text)
VALUES ($1, $2, $3, $4, $5)
`

type AppendDeploymentLogParams struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	DeploymentID uuid.UUID
	Stream       string
	Text         string
}

func (q *Queries) AppendDeploymentLog(ctx context.Context, arg AppendDeploymentLogParams) error {
	_, err := q.db.Exec(ctx, appendDeploymentLog,
		arg.ID,
		arg.OrgID,
		arg.DeploymentID,
		arg.Stream,
		arg.Text,
	)
	return err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (id, org_id, service_id, commit_ref, commit_sha, status)
VALUES ($1, $2, $3, $4, $5, 'queued')
RETURNING id, org_id, service_id, status, commit_sha, commit_ref, image_ref, failure_reason, replaced_deployment_id, created_at, started_at, finished_at
`

type CreateDeploymentParams struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	ServiceID uuid.UUID
	CommitRef *string
	CommitSha *string
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ID,
		arg.OrgID,
		arg.ServiceID,
		arg.CommitRef,
		arg.CommitSha,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ServiceID,
		&i.Status,
		&i.CommitSha,
		&i.CommitRef,
		&i.ImageRef,
		&i.FailureReason,
		&i.ReplacedDeploymentID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (id, org_id, service_id, hostname, ours, verified_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, service_id, hostname, ours, verified_at, created_at
`

type CreateDomainParams struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	ServiceID  uuid.UUID
	Hostname   string
	Ours       bool
	VerifiedAt pgtype.Timestamptz
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain,
		arg.ID,
		arg.OrgID,
		arg.ServiceID,
		arg.Hostname,
		arg.Ours,
		arg.VerifiedAt,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ServiceID,
		&i.Hostname,
		&i.Ours,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPlacement = `-- name: CreatePlacement :one
INSERT INTO placements (id, org_id, deployment_id, server_id, container_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, deployment_id, server_id, container_name, created_at
`

type CreatePlacementParams struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	DeploymentID  uuid.UUID
	ServerID      uuid.UUID
	ContainerName string
}

func (q *Queries) CreatePlacement(ctx context.Context, arg CreatePlacementParams) (Placement, error) {
	row := q.db.QueryRow(ctx, createPlacement,
		arg.ID,
		arg.OrgID,
		arg.DeploymentID,
		arg.ServerID,
		arg.ContainerName,
	)
	var i Placement
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DeploymentID,
		&i.ServerID,
		&i.ContainerName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains WHERE id = $1 AND org_id = $2
`

type DeleteDomainParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteDomain(ctx context.Context, arg DeleteDomainParams) error {
	_, err := q.db.Exec(ctx, deleteDomain, arg.ID, arg.OrgID)
	return err
}

const deleteEnvVar = `-- name: DeleteEnvVar :exec
DELETE FROM env_vars WHERE env_id = $1 AND name = $2
`

type DeleteEnvVarParams struct {
	EnvID uuid.UUID
	Name  string
}

func (q *Queries) DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) error {
	_, err := q.db.Exec(ctx, deleteEnvVar, arg.EnvID, arg.Name)
	return err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, org_id, service_id, status, commit_sha, commit_ref, image_ref, failure_reason, replaced_deployment_id, created_at, started_at, finished_at FROM deployments WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ServiceID,
		&i.Status,
		&i.CommitSha,
		&i.CommitRef,
		&i.ImageRef,
		&i.FailureReason,
		&i.ReplacedDeploymentID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLiveDeployment = `-- name: GetLiveDeployment :one
SELECT id, org_id, service_id, status, commit_sha, commit_ref, image_ref, failure_reason, replaced_deployment_id, created_at, started_at, finished_at FROM deployments WHERE service_id = $1 AND status = 'live'
`

func (q *Queries) GetLiveDeployment(ctx context.Context, serviceID uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getLiveDeployment, serviceID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ServiceID,
		&i.Status,
		&i.CommitSha,
		&i.CommitRef,
		&i.ImageRef,
		&i.FailureReason,
		&i.ReplacedDeploymentID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getServicePort = `-- name: GetServicePort :one
SELECT id, org_id, server_id, port, service_id, purpose, created_at FROM port_allocations WHERE service_id = $1 AND purpose = $2
`

type GetServicePortParams struct {
	ServiceID *uuid.UUID
	Purpose   string
}

func (q *Queries) GetServicePort(ctx context.Context, arg GetServicePortParams) (PortAllocation, error) {
	row := q.db.QueryRow(ctx, getServicePort, arg.ServiceID, arg.Purpose)
	var i PortAllocation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ServerID,
		&i.Port,
		&i.ServiceID,
		&i.Purpose,
		&i.CreatedAt,
	)
	return i, err
}

const listDeploymentLogs = `-- name: ListDeploymentLogs :many
SELECT id, org_id, deployment_id, stream, text, at FROM deployment_logs
WHERE deployment_id = $1 AND at > $2
ORDER BY at
LIMIT $3
`

type ListDeploymentLogsParams struct {
	DeploymentID uuid.UUID
	At           pgtype.Timestamptz
	Limit        int32
}

func (q *Queries) ListDeploymentLogs(ctx context.Context, arg ListDeploymentLogsParams) ([]DeploymentLog, error) {
	rows, err := q.db.Query(ctx, listDeploymentLogs, arg.DeploymentID, arg.At, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentLog
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DeploymentID,
			&i.Stream,
			&i.Text,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, org_id, service_id, status, commit_sha, commit_ref, image_ref, failure_reason, replaced_deployment_id, created_at, started_at, finished_at FROM deployments
WHERE service_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListDeploymentsParams struct {
	ServiceID uuid.UUID
	Limit     int32
}

func (q *Queries) ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeployments, arg.ServiceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ServiceID,
			&i.Status,
			&i.CommitSha,
			&i.CommitRef,
			&i.ImageRef,
			&i.FailureReason,
			&i.ReplacedDeploymentID,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomains = `-- name: ListDomains :many
SELECT id, org_id, service_id, hostname, ours, verified_at, created_at FROM domains WHERE service_id = $1 ORDER BY ours DESC, hostname
`

func (q *Queries) ListDomains(ctx context.Context, serviceID uuid.UUID) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomains, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ServiceID,
			&i.Hostname,
			&i.Ours,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsForServer = `-- name: ListDomainsForServer :many
SELECT d.hostname, d.service_id, s.health_port
FROM domains d
JOIN services s ON s.id = d.service_id
JOIN environments e ON e.id = s.env_id
WHERE e.server_id = $1 AND (d.verified_at IS NOT NULL OR d.ours)
ORDER BY d.hostname
`

type ListDomainsForServerRow struct {
	Hostname   string
	ServiceID  uuid.UUID
	HealthPort *int32
}

// Hostnames the router should answer for on one server.
func (q *Queries) ListDomainsForServer(ctx context.Context, serverID *uuid.UUID) ([]ListDomainsForServerRow, error) {
	rows, err := q.db.Query(ctx, listDomainsForServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDomainsForServerRow
	for rows.Next() {
		var i ListDomainsForServerRow
		if err := rows.Scan(&i.Hostname, &i.ServiceID, &i.HealthPort); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvVarNames = `-- name: ListEnvVarNames :many
SELECT name, updated_at FROM env_vars WHERE env_id = $1 ORDER BY name
`

type ListEnvVarNamesRow struct {
	Name      string
	UpdatedAt pgtype.Timestamptz
}

// Names only, so a client can list them without values ever leaving the control plane.
func (q *Queries) ListEnvVarNames(ctx context.Context, envID uuid.UUID) ([]ListEnvVarNamesRow, error) {
	rows, err := q.db.Query(ctx, listEnvVarNames, envID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnvVarNamesRow
	for rows.Next() {
		var i ListEnvVarNamesRow
		if err := rows.Scan(&i.Name, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvVars = `-- name: ListEnvVars :many
SELECT name, value FROM env_vars WHERE env_id = $1 ORDER BY name
`

type ListEnvVarsRow struct {
	Name  string
	Value []byte
}

func (q *Queries) ListEnvVars(ctx context.Context, envID uuid.UUID) ([]ListEnvVarsRow, error) {
	rows, err := q.db.Query(ctx, listEnvVars, envID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnvVarsRow
	for rows.Next() {
		var i ListEnvVarsRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLivePlacementsForServer = `-- name: ListLivePlacementsForServer :many
SELECT pl.id, pl.org_id, pl.deployment_id, pl.server_id, pl.container_name, pl.created_at, d.image_ref, d.id AS deployment_id, s.id AS service_id, s.name AS service_name,
       s.kind, s.memory_limit_bytes, s.health_path, s.health_port,
       e.id AS environment_id, e.name AS environment_name,
       p.id AS project_id, p.slug AS project_slug
FROM placements pl
JOIN deployments d ON d.id = pl.deployment_id
JOIN services s ON s.id = d.service_id
JOIN environments e ON e.id = s.env_id
JOIN projects p ON p.id = e.project_id
WHERE pl.server_id = $1 AND d.status = 'live'
ORDER BY p.slug, e.name, s.name
`

type ListLivePlacementsForServerRow struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	DeploymentID     uuid.UUID
	ServerID         uuid.UUID
	ContainerName    string
	CreatedAt        pgtype.Timestamptz
	ImageRef         *string
	DeploymentID_2   uuid.UUID
	ServiceID        uuid.UUID
	ServiceName      string
	Kind             ServiceKind
	MemoryLimitBytes int64
	HealthPath       *string
	HealthPort       *int32
	EnvironmentID    uuid.UUID
	EnvironmentName  string
	ProjectID        uuid.UUID
	ProjectSlug      string
}

// Every container that should be running on one server, from the live deployment of each of its
// services. This is what the desired state for a server is built from.
func (q *Queries) ListLivePlacementsForServer(ctx context.Context, serverID uuid.UUID) ([]ListLivePlacementsForServerRow, error) {
	rows, err := q.db.Query(ctx, listLivePlacementsForServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLivePlacementsForServerRow
	for rows.Next() {
		var i ListLivePlacementsForServerRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DeploymentID,
			&i.ServerID,
			&i.ContainerName,
			&i.CreatedAt,
			&i.ImageRef,
			&i.DeploymentID_2,
			&i.ServiceID,
			&i.ServiceName,
			&i.Kind,
			&i.MemoryLimitBytes,
			&i.HealthPath,
			&i.HealthPort,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.ProjectID,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacements = `-- name: ListPlacements :many
SELECT id, org_id, deployment_id, server_id, container_name, created_at FROM placements WHERE deployment_id = $1
`

func (q *Queries) ListPlacements(ctx context.Context, deploymentID uuid.UUID) ([]Placement, error) {
	rows, err := q.db.Query(ctx, listPlacements, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Placement
	for rows.Next() {
		var i Placement
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DeploymentID,
			&i.ServerID,
			&i.ContainerName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortAllocations = `-- name: ListPortAllocations :many
SELECT id, org_id, server_id, port, service_id, purpose, created_at FROM port_allocations WHERE server_id = $1 ORDER BY port
`

func (q *Queries) ListPortAllocations(ctx context.Context, serverID uuid.UUID) ([]PortAllocation, error) {
	rows, err := q.db.Query(ctx, listPortAllocations, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PortAllocation
	for rows.Next() {
		var i PortAllocation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ServerID,
			&i.Port,
			&i.ServiceID,
			&i.Purpose,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDomainVerified = `-- name: MarkDomainVerified :exec
UPDATE domains SET verified_at = now() WHERE id = $1 AND org_id = $2
`

type MarkDomainVerifiedParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) MarkDomainVerified(ctx context.Context, arg MarkDomainVerifiedParams) error {
	_, err := q.db.Exec(ctx, markDomainVerified, arg.ID, arg.OrgID)
	return err
}

const releaseServicePorts = `-- name: ReleaseServicePorts :exec
DELETE FROM port_allocations WHERE service_id = $1
`

func (q *Queries) ReleaseServicePorts(ctx context.Context, serviceID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseServicePorts, serviceID)
	return err
}

const setDeploymentImage = `-- name: SetDeploymentImage :exec
UPDATE deployments SET image_ref = $2, commit_sha = COALESCE($3, commit_sha) WHERE id = $1
`

type SetDeploymentImageParams struct {
	ID        uuid.UUID
	ImageRef  *string
	CommitSha *string
}

func (q *Queries) SetDeploymentImage(ctx context.Context, arg SetDeploymentImageParams) error {
	_, err := q.db.Exec(ctx, setDeploymentImage, arg.ID, arg.ImageRef, arg.CommitSha)
	return err
}

const setDeploymentReplaced = `-- name: SetDeploymentReplaced :exec
UPDATE deployments SET replaced_deployment_id = $2 WHERE id = $1
`

type SetDeploymentReplacedParams struct {
	ID                   uuid.UUID
	ReplacedDeploymentID *uuid.UUID
}

func (q *Queries) SetDeploymentReplaced(ctx context.Context, arg SetDeploymentReplacedParams) error {
	_, err := q.db.Exec(ctx, setDeploymentReplaced, arg.ID, arg.ReplacedDeploymentID)
	return err
}

const setDeploymentStatus = `-- name: SetDeploymentStatus :exec
UPDATE deployments
SET status = $2,
    failure_reason = $3,
    started_at = COALESCE(started_at, CASE WHEN $2 = 'building' THEN now() END),
    finished_at = CASE WHEN $2 IN ('live', 'failed') THEN now() ELSE finished_at END
WHERE id = $1
`

type SetDeploymentStatusParams struct {
	ID            uuid.UUID
	Status        DeploymentStatus
	FailureReason *string
}

func (q *Queries) SetDeploymentStatus(ctx context.Context, arg SetDeploymentStatusParams) error {
	_, err := q.db.Exec(ctx, setDeploymentStatus, arg.ID, arg.Status, arg.FailureReason)
	return err
}

const setEnvVar = `-- name: SetEnvVar :exec
INSERT INTO env_vars (id, org_id, env_id, name, value)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (env_id, name) DO UPDATE
SET value = EXCLUDED.value, updated_at = now()
`

type SetEnvVarParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
	EnvID uuid.UUID
	Name  string
	Value []byte
}

func (q *Queries) SetEnvVar(ctx context.Context, arg SetEnvVarParams) error {
	_, err := q.db.Exec(ctx, setEnvVar,
		arg.ID,
		arg.OrgID,
		arg.EnvID,
		arg.Name,
		arg.Value,
	)
	return err
}

const supersedePreviousDeployments = `-- name: SupersedePreviousDeployments :exec
UPDATE deployments
SET status = 'superseded', finished_at = COALESCE(finished_at, now())
WHERE service_id = $1 AND status = 'live' AND id <> $2
`

type SupersedePreviousDeploymentsParams struct {
	ServiceID uuid.UUID
	ID        uuid.UUID
}

// Only one deployment is live at a time, so the previous one steps aside first.
func (q *Queries) SupersedePreviousDeployments(ctx context.Context, arg SupersedePreviousDeploymentsParams) error {
	_, err := q.db.Exec(ctx, supersedePreviousDeployments, arg.ServiceID, arg.ID)
	return err
}
