// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE invitations SET accepted_at = now() WHERE id = $1
`

func (q *Queries) AcceptInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, acceptInvitation, id)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (id, org_id, email, role, token_hash, invited_by_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, email, role, token_hash, invited_by_id, created_at, expires_at, accepted_at
`

type CreateInvitationParams struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Email       string
	Role        MembershipRole
	TokenHash   []byte
	InvitedByID *uuid.UUID
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedByID,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedByID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations WHERE id = $1 AND org_id = $2
`

type DeleteInvitationParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteInvitation(ctx context.Context, arg DeleteInvitationParams) error {
	_, err := q.db.Exec(ctx, deleteInvitation, arg.ID, arg.OrgID)
	return err
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT id, org_id, email, role, token_hash, invited_by_id, created_at, expires_at, accepted_at FROM invitations
WHERE org_id = $1 AND accepted_at IS NULL AND expires_at > now()
ORDER BY created_at
`

func (q *Queries) ListPendingInvitations(ctx context.Context, orgID uuid.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedByID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
