// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DeploymentStatus string

const (
	DeploymentStatusQueued     DeploymentStatus = "queued"
	DeploymentStatusBuilding   DeploymentStatus = "building"
	DeploymentStatusDeploying  DeploymentStatus = "deploying"
	DeploymentStatusLive       DeploymentStatus = "live"
	DeploymentStatusFailed     DeploymentStatus = "failed"
	DeploymentStatusSuperseded DeploymentStatus = "superseded"
)

func (e *DeploymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentStatus(s)
	case string:
		*e = DeploymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentStatus: %T", src)
	}
	return nil
}

type NullDeploymentStatus struct {
	DeploymentStatus DeploymentStatus
	Valid            bool // Valid is true if DeploymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentStatus), nil
}

type DiscoveredKind string

const (
	DiscoveredKindContainer DiscoveredKind = "container"
	DiscoveredKindImage     DiscoveredKind = "image"
	DiscoveredKindVolume    DiscoveredKind = "volume"
	DiscoveredKindService   DiscoveredKind = "service"
	DiscoveredKindPort      DiscoveredKind = "port"
	DiscoveredKindDatabase  DiscoveredKind = "database"
)

func (e *DiscoveredKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscoveredKind(s)
	case string:
		*e = DiscoveredKind(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscoveredKind: %T", src)
	}
	return nil
}

type NullDiscoveredKind struct {
	DiscoveredKind DiscoveredKind
	Valid          bool // Valid is true if DiscoveredKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscoveredKind) Scan(value interface{}) error {
	if value == nil {
		ns.DiscoveredKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscoveredKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscoveredKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscoveredKind), nil
}

type MembershipRole string

const (
	MembershipRoleOwner  MembershipRole = "owner"
	MembershipRoleAdmin  MembershipRole = "admin"
	MembershipRoleMember MembershipRole = "member"
	MembershipRoleViewer MembershipRole = "viewer"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole
	Valid          bool // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type RoutingMode string

const (
	RoutingModeTakeover    RoutingMode = "takeover"
	RoutingModeBehindProxy RoutingMode = "behind_proxy"
)

func (e *RoutingMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoutingMode(s)
	case string:
		*e = RoutingMode(s)
	default:
		return fmt.Errorf("unsupported scan type for RoutingMode: %T", src)
	}
	return nil
}

type NullRoutingMode struct {
	RoutingMode RoutingMode
	Valid       bool // Valid is true if RoutingMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoutingMode) Scan(value interface{}) error {
	if value == nil {
		ns.RoutingMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoutingMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoutingMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoutingMode), nil
}

type ServerMode string

const (
	ServerModeManaged ServerMode = "managed"
	ServerModeWatch   ServerMode = "watch"
)

func (e *ServerMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServerMode(s)
	case string:
		*e = ServerMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ServerMode: %T", src)
	}
	return nil
}

type NullServerMode struct {
	ServerMode ServerMode
	Valid      bool // Valid is true if ServerMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServerMode) Scan(value interface{}) error {
	if value == nil {
		ns.ServerMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServerMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServerMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServerMode), nil
}

type ServerStatus string

const (
	ServerStatusPending        ServerStatus = "pending"
	ServerStatusSurveying      ServerStatus = "surveying"
	ServerStatusAwaitingChoice ServerStatus = "awaiting_choice"
	ServerStatusInstalling     ServerStatus = "installing"
	ServerStatusOnline         ServerStatus = "online"
	ServerStatusOffline        ServerStatus = "offline"
	ServerStatusFailed         ServerStatus = "failed"
)

func (e *ServerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServerStatus(s)
	case string:
		*e = ServerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ServerStatus: %T", src)
	}
	return nil
}

type NullServerStatus struct {
	ServerStatus ServerStatus
	Valid        bool // Valid is true if ServerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ServerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServerStatus), nil
}

type ServiceKind string

const (
	ServiceKindApp        ServiceKind = "app"
	ServiceKindPostgres   ServiceKind = "postgres"
	ServiceKindMysql      ServiceKind = "mysql"
	ServiceKindRedis      ServiceKind = "redis"
	ServiceKindClickhouse ServiceKind = "clickhouse"
	ServiceKindSqlite     ServiceKind = "sqlite"
	ServiceKindSrs        ServiceKind = "srs"
	ServiceKindMediamtx   ServiceKind = "mediamtx"
)

func (e *ServiceKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServiceKind(s)
	case string:
		*e = ServiceKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ServiceKind: %T", src)
	}
	return nil
}

type NullServiceKind struct {
	ServiceKind ServiceKind
	Valid       bool // Valid is true if ServiceKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServiceKind) Scan(value interface{}) error {
	if value == nil {
		ns.ServiceKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServiceKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServiceKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServiceKind), nil
}

type AuditLog struct {
	ID          uuid.UUID
	OrgID       *uuid.UUID
	ActorUserID *uuid.UUID
	Action      string
	TargetType  string
	TargetID    *uuid.UUID
	Metadata    []byte
	Ip          *netip.Addr
	CreatedAt   pgtype.Timestamptz
}

type Deployment struct {
	ID                   uuid.UUID
	OrgID                uuid.UUID
	ServiceID            uuid.UUID
	Status               DeploymentStatus
	CommitSha            *string
	CommitRef            *string
	ImageRef             *string
	FailureReason        *string
	ReplacedDeploymentID *uuid.UUID
	CreatedAt            pgtype.Timestamptz
	StartedAt            pgtype.Timestamptz
	FinishedAt           pgtype.Timestamptz
}

type DeploymentLog struct {
	ID           uuid.UUID
	OrgID        uuid.UUID
	DeploymentID uuid.UUID
	Stream       string
	Text         string
	At           pgtype.Timestamptz
}

type DiscoveredResource struct {
	ID                        uuid.UUID
	OrgID                     uuid.UUID
	ServerID                  uuid.UUID
	Kind                      DiscoveredKind
	ExternalID                string
	Name                      string
	Status                    *string
	Image                     *string
	Version                   *string
	Ports                     []int32
	SizeBytes                 *int64
	Managed                   bool
	AdoptedAt                 pgtype.Timestamptz
	AdoptedContainerCreatedAt pgtype.Timestamptz
	Details                   []byte
	FirstSeenAt               pgtype.Timestamptz
	LastSeenAt                pgtype.Timestamptz
}

type Domain struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	ServiceID  uuid.UUID
	Hostname   string
	Ours       bool
	VerifiedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type EnvVar struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	EnvID     uuid.UUID
	Name      string
	Value     []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Environment struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	ServerID  *uuid.UUID
	Name      string
	Branch    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type GithubInstallation struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	ExternalID  string
	Account     string
	ConnectedBy *uuid.UUID
	CreatedAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type Invitation struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Email       string
	Role        MembershipRole
	TokenHash   []byte
	InvitedByID *uuid.UUID
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	AcceptedAt  pgtype.Timestamptz
}

type Membership struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	UserID    uuid.UUID
	Role      MembershipRole
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Placement struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	DeploymentID  uuid.UUID
	ServerID      uuid.UUID
	ContainerName string
	CreatedAt     pgtype.Timestamptz
}

type PortAllocation struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	ServerID  uuid.UUID
	Port      int32
	ServiceID *uuid.UUID
	Purpose   string
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID                 uuid.UUID
	OrgID              uuid.UUID
	Name               string
	Slug               string
	RepoProvider       *string
	RepoFullName       *string
	RepoExternalID     *string
	RepoInstallationID *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Server struct {
	ID                  uuid.UUID
	OrgID               uuid.UUID
	Name                string
	Mode                ServerMode
	Status              ServerStatus
	RoutingMode         *RoutingMode
	Host                string
	SshPort             int32
	SshUser             string
	SshSecret           []byte
	SshSecretKind       *string
	AgentTokenHash      []byte
	AgentVersion        *string
	AgentLastSeenAt     pgtype.Timestamptz
	OsName              *string
	OsVersion           *string
	Arch                *string
	Kernel              *string
	CpuCount            *int32
	MemoryBytes         *int64
	DockerVersion       *string
	FailureReason       *string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	EnrollmentTokenHash []byte
	EnrollmentExpiresAt pgtype.Timestamptz
}

type ServerEvent struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	ServerID  uuid.UUID
	Step      string
	Message   string
	Level     string
	CreatedAt pgtype.Timestamptz
}

type Service struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	EnvID            uuid.UUID
	Name             string
	Kind             ServiceKind
	HealthPath       *string
	HealthPort       *int32
	MemoryLimitBytes int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Session struct {
	TokenHash  []byte
	UserID     uuid.UUID
	UserAgent  string
	Ip         *netip.Addr
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type User struct {
	ID              uuid.UUID
	Email           string
	Name            string
	PasswordHash    string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
