// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (id, org_id, project_id, server_id, name, branch)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, project_id, server_id, name, branch, created_at, updated_at
`

type CreateEnvironmentParams struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	ProjectID uuid.UUID
	ServerID  *uuid.UUID
	Name      string
	Branch    string
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.ServerID,
		arg.Name,
		arg.Branch,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.ServerID,
		&i.Name,
		&i.Branch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInstallation = `-- name: CreateInstallation :one
INSERT INTO github_installations (id, org_id, external_id, account, connected_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (external_id) DO UPDATE
SET account = EXCLUDED.account, revoked_at = NULL
RETURNING id, org_id, external_id, account, connected_by, created_at, revoked_at
`

type CreateInstallationParams struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	ExternalID  string
	Account     string
	ConnectedBy *uuid.UUID
}

func (q *Queries) CreateInstallation(ctx context.Context, arg CreateInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, createInstallation,
		arg.ID,
		arg.OrgID,
		arg.ExternalID,
		arg.Account,
		arg.ConnectedBy,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ExternalID,
		&i.Account,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, org_id, name, slug, repo_provider, repo_full_name, repo_external_id, repo_installation_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, name, slug, repo_provider, repo_full_name, repo_external_id, repo_installation_id, created_at, updated_at
`

type CreateProjectParams struct {
	ID                 uuid.UUID
	OrgID              uuid.UUID
	Name               string
	Slug               string
	RepoProvider       *string
	RepoFullName       *string
	RepoExternalID     *string
	RepoInstallationID *string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.RepoProvider,
		arg.RepoFullName,
		arg.RepoExternalID,
		arg.RepoInstallationID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.RepoProvider,
		&i.RepoFullName,
		&i.RepoExternalID,
		&i.RepoInstallationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (id, org_id, env_id, name, kind, health_path, health_port, memory_limit_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, env_id, name, kind, health_path, health_port, memory_limit_bytes, created_at, updated_at
`

type CreateServiceParams struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	EnvID            uuid.UUID
	Name             string
	Kind             ServiceKind
	HealthPath       *string
	HealthPort       *int32
	MemoryLimitBytes int64
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.ID,
		arg.OrgID,
		arg.EnvID,
		arg.Name,
		arg.Kind,
		arg.HealthPath,
		arg.HealthPort,
		arg.MemoryLimitBytes,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EnvID,
		&i.Name,
		&i.Kind,
		&i.HealthPath,
		&i.HealthPort,
		&i.MemoryLimitBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInstallation = `-- name: DeleteInstallation :exec
DELETE FROM github_installations WHERE org_id = $1 AND external_id = $2
`

type DeleteInstallationParams struct {
	OrgID      uuid.UUID
	ExternalID string
}

func (q *Queries) DeleteInstallation(ctx context.Context, arg DeleteInstallationParams) error {
	_, err := q.db.Exec(ctx, deleteInstallation, arg.OrgID, arg.ExternalID)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1 AND org_id = $2
`

type DeleteProjectParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.OrgID)
	return err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1 AND org_id = $2
`

type DeleteServiceParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteService(ctx context.Context, arg DeleteServiceParams) error {
	_, err := q.db.Exec(ctx, deleteService, arg.ID, arg.OrgID)
	return err
}

const findEnvironmentsForBranch = `-- name: FindEnvironmentsForBranch :many
SELECT e.id, e.org_id, e.project_id, e.server_id, e.name, e.branch, e.created_at, e.updated_at FROM environments e
JOIN projects p ON p.id = e.project_id
WHERE p.repo_external_id = $1 AND e.branch = $2
`

type FindEnvironmentsForBranchParams struct {
	RepoExternalID *string
	Branch         string
}

// Used to decide what a push should deploy.
func (q *Queries) FindEnvironmentsForBranch(ctx context.Context, arg FindEnvironmentsForBranchParams) ([]Environment, error) {
	rows, err := q.db.Query(ctx, findEnvironmentsForBranch, arg.RepoExternalID, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.ServerID,
			&i.Name,
			&i.Branch,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeployTarget = `-- name: GetDeployTarget :one
SELECT p.org_id, p.id AS project_id, e.id AS environment_id, s.id AS service_id, e.server_id,
       e.branch, p.repo_full_name, p.repo_installation_id
FROM environments e
JOIN projects p ON p.id = e.project_id
JOIN services s ON s.env_id = e.id AND s.kind = 'app'
WHERE e.id = $1
`

type GetDeployTargetRow struct {
	OrgID              uuid.UUID
	ProjectID          uuid.UUID
	EnvironmentID      uuid.UUID
	ServiceID          uuid.UUID
	ServerID           *uuid.UUID
	Branch             string
	RepoFullName       *string
	RepoInstallationID *string
}

// Everything a deploy of one environment needs, in one read. Scoped by row level security like
// every other query here, unlike the pre-identity lookup a push goes through.
func (q *Queries) GetDeployTarget(ctx context.Context, id uuid.UUID) (GetDeployTargetRow, error) {
	row := q.db.QueryRow(ctx, getDeployTarget, id)
	var i GetDeployTargetRow
	err := row.Scan(
		&i.OrgID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.ServiceID,
		&i.ServerID,
		&i.Branch,
		&i.RepoFullName,
		&i.RepoInstallationID,
	)
	return i, err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, org_id, project_id, server_id, name, branch, created_at, updated_at FROM environments WHERE id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.ServerID,
		&i.Name,
		&i.Branch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallation = `-- name: GetInstallation :one
SELECT id, org_id, external_id, account, connected_by, created_at, revoked_at FROM github_installations WHERE org_id = $1 AND external_id = $2 AND revoked_at IS NULL
`

type GetInstallationParams struct {
	OrgID      uuid.UUID
	ExternalID string
}

func (q *Queries) GetInstallation(ctx context.Context, arg GetInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallation, arg.OrgID, arg.ExternalID)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ExternalID,
		&i.Account,
		&i.ConnectedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, name, slug, repo_provider, repo_full_name, repo_external_id, repo_installation_id, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.RepoProvider,
		&i.RepoFullName,
		&i.RepoExternalID,
		&i.RepoInstallationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, org_id, name, slug, repo_provider, repo_full_name, repo_external_id, repo_installation_id, created_at, updated_at FROM projects WHERE org_id = $1 AND slug = $2
`

type GetProjectBySlugParams struct {
	OrgID uuid.UUID
	Slug  string
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, arg.OrgID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.RepoProvider,
		&i.RepoFullName,
		&i.RepoExternalID,
		&i.RepoInstallationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getService = `-- name: GetService :one
SELECT id, org_id, env_id, name, kind, health_path, health_port, memory_limit_bytes, created_at, updated_at FROM services WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EnvID,
		&i.Name,
		&i.Kind,
		&i.HealthPath,
		&i.HealthPort,
		&i.MemoryLimitBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, org_id, project_id, server_id, name, branch, created_at, updated_at FROM environments WHERE project_id = $1 ORDER BY name
`

func (q *Queries) ListEnvironments(ctx context.Context, projectID uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.ServerID,
			&i.Name,
			&i.Branch,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallations = `-- name: ListInstallations :many
SELECT id, org_id, external_id, account, connected_by, created_at, revoked_at FROM github_installations
WHERE org_id = $1 AND revoked_at IS NULL
ORDER BY account
`

func (q *Queries) ListInstallations(ctx context.Context, orgID uuid.UUID) ([]GithubInstallation, error) {
	rows, err := q.db.Query(ctx, listInstallations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubInstallation
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ExternalID,
			&i.Account,
			&i.ConnectedBy,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, org_id, name, slug, repo_provider, repo_full_name, repo_external_id, repo_installation_id, created_at, updated_at FROM projects WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context, orgID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.RepoProvider,
			&i.RepoFullName,
			&i.RepoExternalID,
			&i.RepoInstallationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, org_id, env_id, name, kind, health_path, health_port, memory_limit_bytes, created_at, updated_at FROM services WHERE env_id = $1 ORDER BY kind, name
`

func (q *Queries) ListServices(ctx context.Context, envID uuid.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices, envID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.EnvID,
			&i.Name,
			&i.Kind,
			&i.HealthPath,
			&i.HealthPort,
			&i.MemoryLimitBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesForServer = `-- name: ListServicesForServer :many
SELECT s.id, s.org_id, s.env_id, s.name, s.kind, s.health_path, s.health_port, s.memory_limit_bytes, s.created_at, s.updated_at, e.id AS environment_id, e.name AS environment_name, p.slug AS project_slug
FROM services s
JOIN environments e ON e.id = s.env_id
JOIN projects p ON p.id = e.project_id
WHERE e.server_id = $1
ORDER BY p.slug, e.name, s.name
`

type ListServicesForServerRow struct {
	ID               uuid.UUID
	OrgID            uuid.UUID
	EnvID            uuid.UUID
	Name             string
	Kind             ServiceKind
	HealthPath       *string
	HealthPort       *int32
	MemoryLimitBytes int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	EnvironmentID    uuid.UUID
	EnvironmentName  string
	ProjectSlug      string
}

// Everything the agent on one server needs to run, across every project placed there.
func (q *Queries) ListServicesForServer(ctx context.Context, serverID *uuid.UUID) ([]ListServicesForServerRow, error) {
	rows, err := q.db.Query(ctx, listServicesForServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesForServerRow
	for rows.Next() {
		var i ListServicesForServerRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.EnvID,
			&i.Name,
			&i.Kind,
			&i.HealthPath,
			&i.HealthPort,
			&i.MemoryLimitBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnvironmentID,
			&i.EnvironmentName,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInstallation = `-- name: RevokeInstallation :exec
SELECT revoke_installation($1)
`

func (q *Queries) RevokeInstallation(ctx context.Context, pExternalID string) error {
	_, err := q.db.Exec(ctx, revokeInstallation, pExternalID)
	return err
}

const setEnvironmentBranch = `-- name: SetEnvironmentBranch :exec
UPDATE environments SET branch = $2, updated_at = now() WHERE id = $1
`

type SetEnvironmentBranchParams struct {
	ID     uuid.UUID
	Branch string
}

func (q *Queries) SetEnvironmentBranch(ctx context.Context, arg SetEnvironmentBranchParams) error {
	_, err := q.db.Exec(ctx, setEnvironmentBranch, arg.ID, arg.Branch)
	return err
}

const setEnvironmentServer = `-- name: SetEnvironmentServer :exec
UPDATE environments SET server_id = $2, updated_at = now() WHERE id = $1
`

type SetEnvironmentServerParams struct {
	ID       uuid.UUID
	ServerID *uuid.UUID
}

func (q *Queries) SetEnvironmentServer(ctx context.Context, arg SetEnvironmentServerParams) error {
	_, err := q.db.Exec(ctx, setEnvironmentServer, arg.ID, arg.ServerID)
	return err
}

const setProjectRepository = `-- name: SetProjectRepository :one
UPDATE projects
SET repo_provider = $2, repo_full_name = $3, repo_external_id = $4, repo_installation_id = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, org_id, name, slug, repo_provider, repo_full_name, repo_external_id, repo_installation_id, created_at, updated_at
`

type SetProjectRepositoryParams struct {
	ID                 uuid.UUID
	RepoProvider       *string
	RepoFullName       *string
	RepoExternalID     *string
	RepoInstallationID *string
}

func (q *Queries) SetProjectRepository(ctx context.Context, arg SetProjectRepositoryParams) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectRepository,
		arg.ID,
		arg.RepoProvider,
		arg.RepoFullName,
		arg.RepoExternalID,
		arg.RepoInstallationID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.RepoProvider,
		&i.RepoFullName,
		&i.RepoExternalID,
		&i.RepoInstallationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET health_path = $2, health_port = $3, memory_limit_bytes = $4, updated_at = now()
WHERE id = $1
RETURNING id, org_id, env_id, name, kind, health_path, health_port, memory_limit_bytes, created_at, updated_at
`

type UpdateServiceParams struct {
	ID               uuid.UUID
	HealthPath       *string
	HealthPort       *int32
	MemoryLimitBytes int64
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.HealthPath,
		arg.HealthPort,
		arg.MemoryLimitBytes,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EnvID,
		&i.Name,
		&i.Kind,
		&i.HealthPath,
		&i.HealthPort,
		&i.MemoryLimitBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
