// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: servers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adoptDiscoveredResource = `-- name: AdoptDiscoveredResource :one
UPDATE discovered_resources
SET adopted_at = now(), adopted_container_created_at = $3
WHERE server_id = $1 AND id = $2 AND kind = 'container'
RETURNING id, org_id, server_id, kind, external_id, name, status, image, version, ports, size_bytes, managed, adopted_at, adopted_container_created_at, details, first_seen_at, last_seen_at
`

type AdoptDiscoveredResourceParams struct {
	ServerID                  uuid.UUID
	ID                        uuid.UUID
	AdoptedContainerCreatedAt pgtype.Timestamptz
}

func (q *Queries) AdoptDiscoveredResource(ctx context.Context, arg AdoptDiscoveredResourceParams) (DiscoveredResource, error) {
	row := q.db.QueryRow(ctx, adoptDiscoveredResource, arg.ServerID, arg.ID, arg.AdoptedContainerCreatedAt)
	var i DiscoveredResource
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ServerID,
		&i.Kind,
		&i.ExternalID,
		&i.Name,
		&i.Status,
		&i.Image,
		&i.Version,
		&i.Ports,
		&i.SizeBytes,
		&i.Managed,
		&i.AdoptedAt,
		&i.AdoptedContainerCreatedAt,
		&i.Details,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const clearServerPassword = `-- name: ClearServerPassword :exec
UPDATE servers
SET ssh_secret = NULL, ssh_secret_kind = NULL, updated_at = now()
WHERE id = $1 AND ssh_secret_kind = 'password'
`

// Called the moment setup finishes: we should not hold a customer's server password.
func (q *Queries) ClearServerPassword(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearServerPassword, id)
	return err
}

const createServer = `-- name: CreateServer :one
INSERT INTO servers (id, org_id, name, mode, host, ssh_port, ssh_user, ssh_secret, ssh_secret_kind)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, name, mode, status, routing_mode, host, ssh_port, ssh_user, ssh_secret, ssh_secret_kind, agent_token_hash, agent_version, agent_last_seen_at, os_name, os_version, arch, kernel, cpu_count, memory_bytes, docker_version, failure_reason, created_at, updated_at
`

type CreateServerParams struct {
	ID            uuid.UUID
	OrgID         uuid.UUID
	Name          string
	Mode          ServerMode
	Host          string
	SshPort       int32
	SshUser       string
	SshSecret     []byte
	SshSecretKind *string
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Mode,
		arg.Host,
		arg.SshPort,
		arg.SshUser,
		arg.SshSecret,
		arg.SshSecretKind,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Mode,
		&i.Status,
		&i.RoutingMode,
		&i.Host,
		&i.SshPort,
		&i.SshUser,
		&i.SshSecret,
		&i.SshSecretKind,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.AgentLastSeenAt,
		&i.OsName,
		&i.OsVersion,
		&i.Arch,
		&i.Kernel,
		&i.CpuCount,
		&i.MemoryBytes,
		&i.DockerVersion,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers WHERE id = $1 AND org_id = $2
`

type DeleteServerParams struct {
	ID    uuid.UUID
	OrgID uuid.UUID
}

func (q *Queries) DeleteServer(ctx context.Context, arg DeleteServerParams) error {
	_, err := q.db.Exec(ctx, deleteServer, arg.ID, arg.OrgID)
	return err
}

const deleteStaleDiscoveredResources = `-- name: DeleteStaleDiscoveredResources :execrows
DELETE FROM discovered_resources
WHERE server_id = $1 AND last_seen_at < $2 AND adopted_at IS NULL
`

type DeleteStaleDiscoveredResourcesParams struct {
	ServerID   uuid.UUID
	LastSeenAt pgtype.Timestamptz
}

// Anything not seen in the latest report has gone from the machine.
func (q *Queries) DeleteStaleDiscoveredResources(ctx context.Context, arg DeleteStaleDiscoveredResourcesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleDiscoveredResources, arg.ServerID, arg.LastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServer = `-- name: GetServer :one
SELECT id, org_id, name, mode, status, routing_mode, host, ssh_port, ssh_user, ssh_secret, ssh_secret_kind, agent_token_hash, agent_version, agent_last_seen_at, os_name, os_version, arch, kernel, cpu_count, memory_bytes, docker_version, failure_reason, created_at, updated_at FROM servers WHERE id = $1
`

func (q *Queries) GetServer(ctx context.Context, id uuid.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, getServer, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Mode,
		&i.Status,
		&i.RoutingMode,
		&i.Host,
		&i.SshPort,
		&i.SshUser,
		&i.SshSecret,
		&i.SshSecretKind,
		&i.AgentTokenHash,
		&i.AgentVersion,
		&i.AgentLastSeenAt,
		&i.OsName,
		&i.OsVersion,
		&i.Arch,
		&i.Kernel,
		&i.CpuCount,
		&i.MemoryBytes,
		&i.DockerVersion,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDiscoveredResources = `-- name: ListDiscoveredResources :many
SELECT id, org_id, server_id, kind, external_id, name, status, image, version, ports, size_bytes, managed, adopted_at, adopted_container_created_at, details, first_seen_at, last_seen_at FROM discovered_resources
WHERE server_id = $1
ORDER BY kind, name
`

func (q *Queries) ListDiscoveredResources(ctx context.Context, serverID uuid.UUID) ([]DiscoveredResource, error) {
	rows, err := q.db.Query(ctx, listDiscoveredResources, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveredResource
	for rows.Next() {
		var i DiscoveredResource
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ServerID,
			&i.Kind,
			&i.ExternalID,
			&i.Name,
			&i.Status,
			&i.Image,
			&i.Version,
			&i.Ports,
			&i.SizeBytes,
			&i.Managed,
			&i.AdoptedAt,
			&i.AdoptedContainerCreatedAt,
			&i.Details,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServerEvents = `-- name: ListServerEvents :many
SELECT id, org_id, server_id, step, message, level, created_at FROM server_events
WHERE server_id = $1 AND created_at > $2
ORDER BY created_at
`

type ListServerEventsParams struct {
	ServerID  uuid.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListServerEvents(ctx context.Context, arg ListServerEventsParams) ([]ServerEvent, error) {
	rows, err := q.db.Query(ctx, listServerEvents, arg.ServerID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServerEvent
	for rows.Next() {
		var i ServerEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ServerID,
			&i.Step,
			&i.Message,
			&i.Level,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServers = `-- name: ListServers :many
SELECT id, org_id, name, mode, status, routing_mode, host, ssh_port, ssh_user, ssh_secret, ssh_secret_kind, agent_token_hash, agent_version, agent_last_seen_at, os_name, os_version, arch, kernel, cpu_count, memory_bytes, docker_version, failure_reason, created_at, updated_at FROM servers WHERE org_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListServers(ctx context.Context, orgID uuid.UUID) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Server
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Mode,
			&i.Status,
			&i.RoutingMode,
			&i.Host,
			&i.SshPort,
			&i.SshUser,
			&i.SshSecret,
			&i.SshSecretKind,
			&i.AgentTokenHash,
			&i.AgentVersion,
			&i.AgentLastSeenAt,
			&i.OsName,
			&i.OsVersion,
			&i.Arch,
			&i.Kernel,
			&i.CpuCount,
			&i.MemoryBytes,
			&i.DockerVersion,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDiscoveredResource = `-- name: RecordDiscoveredResource :exec
INSERT INTO discovered_resources (
    id, org_id, server_id, kind, external_id, name, status, image, version, ports,
    size_bytes, managed, details, first_seen_at, last_seen_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, now(), now())
ON CONFLICT (server_id, kind, external_id) DO UPDATE
SET name = EXCLUDED.name,
    status = EXCLUDED.status,
    image = EXCLUDED.image,
    version = EXCLUDED.version,
    ports = EXCLUDED.ports,
    size_bytes = EXCLUDED.size_bytes,
    managed = EXCLUDED.managed,
    details = EXCLUDED.details,
    last_seen_at = now()
`

type RecordDiscoveredResourceParams struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	ServerID   uuid.UUID
	Kind       DiscoveredKind
	ExternalID string
	Name       string
	Status     *string
	Image      *string
	Version    *string
	Ports      []int32
	SizeBytes  *int64
	Managed    bool
	Details    []byte
}

// Upsert so a repeated survey updates rather than duplicates, and first_seen_at is kept.
func (q *Queries) RecordDiscoveredResource(ctx context.Context, arg RecordDiscoveredResourceParams) error {
	_, err := q.db.Exec(ctx, recordDiscoveredResource,
		arg.ID,
		arg.OrgID,
		arg.ServerID,
		arg.Kind,
		arg.ExternalID,
		arg.Name,
		arg.Status,
		arg.Image,
		arg.Version,
		arg.Ports,
		arg.SizeBytes,
		arg.Managed,
		arg.Details,
	)
	return err
}

const recordServerEvent = `-- name: RecordServerEvent :one
INSERT INTO server_events (id, org_id, server_id, step, message, level)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, server_id, step, message, level, created_at
`

type RecordServerEventParams struct {
	ID       uuid.UUID
	OrgID    uuid.UUID
	ServerID uuid.UUID
	Step     string
	Message  string
	Level    string
}

func (q *Queries) RecordServerEvent(ctx context.Context, arg RecordServerEventParams) (ServerEvent, error) {
	row := q.db.QueryRow(ctx, recordServerEvent,
		arg.ID,
		arg.OrgID,
		arg.ServerID,
		arg.Step,
		arg.Message,
		arg.Level,
	)
	var i ServerEvent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ServerID,
		&i.Step,
		&i.Message,
		&i.Level,
		&i.CreatedAt,
	)
	return i, err
}

const releaseDiscoveredResource = `-- name: ReleaseDiscoveredResource :exec
UPDATE discovered_resources
SET adopted_at = NULL, adopted_container_created_at = NULL
WHERE server_id = $1 AND id = $2
`

type ReleaseDiscoveredResourceParams struct {
	ServerID uuid.UUID
	ID       uuid.UUID
}

// Releasing touches the container itself not at all.
func (q *Queries) ReleaseDiscoveredResource(ctx context.Context, arg ReleaseDiscoveredResourceParams) error {
	_, err := q.db.Exec(ctx, releaseDiscoveredResource, arg.ServerID, arg.ID)
	return err
}

const setServerAgentToken = `-- name: SetServerAgentToken :exec
UPDATE servers SET agent_token_hash = $2, updated_at = now() WHERE id = $1
`

type SetServerAgentTokenParams struct {
	ID             uuid.UUID
	AgentTokenHash []byte
}

func (q *Queries) SetServerAgentToken(ctx context.Context, arg SetServerAgentTokenParams) error {
	_, err := q.db.Exec(ctx, setServerAgentToken, arg.ID, arg.AgentTokenHash)
	return err
}

const setServerRoutingMode = `-- name: SetServerRoutingMode :exec
UPDATE servers SET routing_mode = $2, updated_at = now() WHERE id = $1
`

type SetServerRoutingModeParams struct {
	ID          uuid.UUID
	RoutingMode *RoutingMode
}

func (q *Queries) SetServerRoutingMode(ctx context.Context, arg SetServerRoutingModeParams) error {
	_, err := q.db.Exec(ctx, setServerRoutingMode, arg.ID, arg.RoutingMode)
	return err
}

const touchServerAgent = `-- name: TouchServerAgent :exec
UPDATE servers
SET agent_last_seen_at = now(), agent_version = $2, status = 'online', updated_at = now()
WHERE id = $1
`

type TouchServerAgentParams struct {
	ID           uuid.UUID
	AgentVersion *string
}

func (q *Queries) TouchServerAgent(ctx context.Context, arg TouchServerAgentParams) error {
	_, err := q.db.Exec(ctx, touchServerAgent, arg.ID, arg.AgentVersion)
	return err
}

const updateServerFacts = `-- name: UpdateServerFacts :exec
UPDATE servers
SET os_name = $2, os_version = $3, arch = $4, kernel = $5,
    cpu_count = $6, memory_bytes = $7, docker_version = $8, updated_at = now()
WHERE id = $1
`

type UpdateServerFactsParams struct {
	ID            uuid.UUID
	OsName        *string
	OsVersion     *string
	Arch          *string
	Kernel        *string
	CpuCount      *int32
	MemoryBytes   *int64
	DockerVersion *string
}

func (q *Queries) UpdateServerFacts(ctx context.Context, arg UpdateServerFactsParams) error {
	_, err := q.db.Exec(ctx, updateServerFacts,
		arg.ID,
		arg.OsName,
		arg.OsVersion,
		arg.Arch,
		arg.Kernel,
		arg.CpuCount,
		arg.MemoryBytes,
		arg.DockerVersion,
	)
	return err
}

const updateServerStatus = `-- name: UpdateServerStatus :exec
UPDATE servers
SET status = $2, failure_reason = $3, updated_at = now()
WHERE id = $1
`

type UpdateServerStatusParams struct {
	ID            uuid.UUID
	Status        ServerStatus
	FailureReason *string
}

func (q *Queries) UpdateServerStatus(ctx context.Context, arg UpdateServerStatusParams) error {
	_, err := q.db.Exec(ctx, updateServerStatus, arg.ID, arg.Status, arg.FailureReason)
	return err
}
