// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, user_agent, ip, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	UserAgent string
	Ip        *netip.Addr
	ExpiresAt pgtype.Timestamptz
}

// No RETURNING for the same reason as CreateUser: the session being created is what will
// identify the caller, so it cannot yet be read back.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSessionsForUser = `-- name: ListSessionsForUser :many

SELECT token_hash, user_agent, ip, created_at, last_seen_at, expires_at
FROM sessions
WHERE user_id = $1 AND expires_at > now()
ORDER BY last_seen_at DESC
`

type ListSessionsForUserRow struct {
	TokenHash  []byte
	UserAgent  string
	Ip         *netip.Addr
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

// Reading and discarding a session by token goes through authenticate_session and
// delete_session, because a token must be resolved before there is a current user for the
// tenant policies to compare against.
func (q *Queries) ListSessionsForUser(ctx context.Context, userID uuid.UUID) ([]ListSessionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsForUserRow
	for rows.Next() {
		var i ListSessionsForUserRow
		if err := rows.Scan(
			&i.TokenHash,
			&i.UserAgent,
			&i.Ip,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
